[project]
name = "dvc-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dvc>=3.66.1",
    "dvc-gs>=3.0.2",
    "pandas>=2.0.0",
    "scikit-learn>=1.3.0",
]
